name: Creating a release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Substitute Manifest and Download Links For Versioned Ones
      run: |
        VERSION="${{ github.event.release.tag_name }}"
        VERSION="${VERSION#v}"
        jq \
          --arg version "$VERSION" \
          --arg url "https://github.com/${{ github.repository }}" \
          --arg manifest "https://github.com/${{ github.repository }}/releases/latest/download/module.json" \
          --arg download "https://github.com/${{ github.repository }}/releases/download/${{ github.event.release.tag_name }}/module.zip" \
          '.version = $version | .url = $url | .manifest = $manifest | .download = $download' \
          module.json > module.tmp.json && mv module.tmp.json module.json

    - run: zip -r ./module.zip module.json LICENSE styles/ scripts/ templates/ languages/ images/

    - name: Upload release assets
      run: gh release upload ${{ github.event.release.tag_name }} ./module.json ./module.zip --clobber
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
